/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppHomeIndexRouteImport } from './pages/_app/_home/index'
import { Route as AppCvsIndexRouteImport } from './pages/_app/cvs/index'
import { Route as AppGeneratorIndexRouteImport } from './pages/_app/generator/index'

const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/_app/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCvsIndexRoute = AppCvsIndexRouteImport.update({
  id: '/_app/cvs/',
  path: '/cvs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGeneratorIndexRoute = AppGeneratorIndexRouteImport.update({
  id: '/_app/generator/',
  path: '/generator/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppHomeIndexRoute
  '/cvs/': typeof AppCvsIndexRoute
  '/generator/': typeof AppGeneratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppHomeIndexRoute
  '/cvs': typeof AppCvsIndexRoute
  '/generator': typeof AppGeneratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_home/': typeof AppHomeIndexRoute
  '/_app/cvs/': typeof AppCvsIndexRoute
  '/_app/generator/': typeof AppGeneratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cvs/' | '/generator/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cvs' | '/generator'
  id: '__root__' | '/_app/_home/' | '/_app/cvs/' | '/_app/generator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppCvsIndexRoute: typeof AppCvsIndexRoute
  AppGeneratorIndexRoute: typeof AppGeneratorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/_home/': {
      id: '/_app/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cvs/': {
      id: '/_app/cvs/'
      path: '/cvs'
      fullPath: '/cvs/'
      preLoaderRoute: typeof AppCvsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/generator/': {
      id: '/_app/generator/'
      path: '/generator'
      fullPath: '/generator/'
      preLoaderRoute: typeof AppGeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppCvsIndexRoute: AppCvsIndexRoute,
  AppGeneratorIndexRoute: AppGeneratorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
